version: '3'
services:
  reverseproxy:
    build:
      context: .
    image: lemix777/reverseproxy
  backend_user:
    build:
      context: ../../restapi-user
    image: lemix777/restapi-user
  backend_feed:
    build:
      context: ../../restapi-feed
    image: lemix777/restapi-feed
  frontend:
    build:
      context: ../../frontend
    image: lemix777/frontend:latest
