apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
data:
  credentials: W1NlcnZlcmxlc3MtRGVwbG95XQphd3NfYWNjZXNzX2tleV9pZD1BS0lBVENYR1pVQU9ORENWQlk3
Qgphd3Nfc2VjcmV0X2FjY2Vzc19rZXk9V0hHR1h1QVNZS2RkcE5qdmMvRmhJTnpwallDeHA2Sk1y
eUJMNytoVAoKW2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkPUFLSUFaN0xMRk1ZS1YzS0U1SlNR
CmF3c19zZWNyZXRfYWNjZXNzX2tleT1lV1BZN0JmbUFJNm5QYjhoUlVIODRkODI1clVOa3VmQlYw
M25XQy96Cgpbc2VydmVybGVzc10KYXdzX2FjY2Vzc19rZXlfaWQ9QUtJQVo3TExGTVlLVFFIVEhT
NzcKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5PWJKZmxNVVN4VHJNU3NQWUZtZ2x4QXZzMWhEQkJoVFB2
WWowUVRxL2IK 